apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.faraday.env.pgsql_host }}
  labels:
    app: {{ .Values.faraday.env.pgsql_host }}
spec:
  ports:
  - port: {{ .Values.postgre.statefulset.port }}
    name: database
  clusterIP: None
  selector:
    app: {{ .Values.faraday.env.pgsql_host }}