apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: faraday-db
spec:
  selector:
    matchLabels:
      app: faraday-db
  serviceName: faraday-db
  replicas: 1
  template:
    metadata:
      labels:
        app: faraday-db
    spec:
      containers:
      - name: app
        image: postgres:12.7-alpine
        ports:
        - containerPort: 5432
          name: database
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: faraday
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: faraday-postgre-volume
      volumes:
        - name: faraday-postgre-volume
          persistentVolumeClaim:
          claimName: faraday-postgre-volume