apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgre.pvc.name }}
spec:
  accessModes:
    - {{ .Values.postgre.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.postgre.pvc.storage }}
  storageClassName: {{ .Values.postgre.storageClassName }}